name: ParaBank Capstone CI/CD

on:
  workflow_dispatch:

jobs:
  automation-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Workflow Disabled
        run: echo "Workflow is configured for manual execution only."